# Ingress disabled - using LoadBalancer service instead
# Uncomment and configure when you have a domain

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nestjs-app-ingress
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     nginx.ingress.kubernetes.io/ssl-redirect: "true"
# spec:
#   tls:
#   - hosts:
#     - your-domain.com
#     secretName: nestjs-app-tls
#   rules:
#   - host: your-domain.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: nestjs-app-service
#             port:
#               number: 80
