apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: cG9zdGdyZXM=  # base64 encoded "postgres"
  password: cG9zdGdyZXM=  # base64 encoded "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: # This will be created by the workflow
